BES API Client
SEED-platform/py-bes pull request #1
Opened 2017-05-08 18:00 UTC by tallus

- client for accessing the BES  API v1 & v2
    - tests

2017-05-10 21:54 UTC, fablet requested changes
The only py3 issues I can across were the basestring problem we talked about and two uses of iteritems, both noted in line comments.  If those changes are made then all tests, other than the one noted problem test, pass in py 2.7, 3.4, 3.5 and 3.6. I have a tox setup and ready to add if you want.
Pylint flags several whitespace errors, but it looks like most of the remaining pylint issues are by choice and may benefit from local overrides.

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +# Config/Constants
I like your sys.version_info approach to the basestring, py3, compatibility issue, but what about simplifying it further to:
```
PY3 = sys.version_info[0] == 3
if PY3:
    basestring = str
```

2017-05-10 21:54 UTC, fablet commented on pybes/tests/test_pybes.py
> +            error.message, 'Test: 404 test: error, error: test'
this test is problematic.  It passes sometimes and fails others.  I believe it is because sometimes the error message is 
'Test: 404 test: error, error: test' and other times it is 'Test: 404 error: test, test: error' since the portion of the message after '404' is constructed from an unordered dict

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +    for key, val in params.iteritems():
so far, the iteritems calls seem to be the only other py3 incompatibility I have found.  We can run the 2to3 migration tool if you like, but since you only have this in two place, plus one mention in a docstring, they could just manually be changed to
```
iter(parms.items())
```

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        key: val for key, val in dct.iteritems()
the other iteritems() usage. see above.
```
iter(dct.items())
```

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        email, password and organization_token in order to authenticate.
While I can see you are implementing this correctly, this docstring _reads_ as counter to BES documentation which states that the the organization_token is only used for creating a user and getting an access token for that user, from which point it is the access token that you need

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        user_id = None
since user_id and token aren't being changed by any kind of branching statement in this method, PyCharm is flagging a 'value is not used' warning

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        :param default: default error messagee
type in word message

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +            pass
Unnecessary pass statement

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        len(pwd.intersection(UPPERCASE)) and len(pwd.intersection(LOWERCASE))
pylint flags this for using len() as a condition value and in this case is not necessary, all tests pass if you remove len() from each of the intersection checks

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        api_call = requests.put(url, **payload)
unused value, this line is repeated at the bottom of the method

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        api_call = requests.patch(url, **payload)
unused value, this line is repeated at the bottom of the method

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        self._delete(endpoint, id=id)
forgot to add the _check_call_success call to this delete method

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        :param /dimension_3: optional Length of dimension 3 (in feet).
there is a '/' character in front of the 'dimension_3' param name.  also several param :type : blocks in this docstring need to have the the param name added, as in 
```
:type vertices: str 
```
rather than
```
:type str:
```

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        :raises: BES/APIError
repeat of docstring notes from previous method

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        if needed). block_ at the beginning may be ommited
typo in convenience and omitted 
in param list, typo in resource_id in name block and in kwargs in type block.
should :name and :rname be :type and :rtype?

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        if needed). block_ at the beginning may be ommited
typo in convenience and omitted again and the :name vs :type
same docstring issues for get_block_resource, get_block_resources, and update_block_resource below

2017-05-10 21:54 UTC, fablet commented on pybes/pybes.py
> +        :param name: name of building
no 'name' param in signature

2017-05-10 23:49 UTC, tallus commented on pybes/pybes.py
> +    for key, val in params.iteritems():
using items is probably sufficient here

2017-05-11 00:07 UTC, tallus commented on pybes/pybes.py
> +        email, password and organization_token in order to authenticate.
I added the ability  to reuse tokens later as api calls are rate limiteds, I will update the docs accordingly.

2017-05-11 00:10 UTC, tallus commented on pybes/pybes.py
> +        user_id = None
I think that was a hold over as formerly _authenticate was always called but checked for null values

2017-05-11 00:10 UTC, tallus commented on pybes/pybes.py
> +        :param default: default error messagee
???

2017-05-11 00:14 UTC, fablet commented on pybes/pybes.py
> +        :param default: default error messagee
you have an extra 'e' -> messagee

2017-05-11 01:24 UTC, tallus commented
Fixes in.

2017-05-11 16:55 UTC, tallus commented on pybes/tests/test_pybes.py
> +            error.message, 'Test: 404 test: error, error: test'
fixed

2017-05-25 18:29 UTC, fablet approved these changes

2017-06-15 23:52 UTC, merged